In [ ]:
import numpy as np


In [ ]:

x= np.array([12,14,156,25,300])
x

array([ 12,  14, 156,  25, 300])

In [ ]:
x.shape

(5,)

In [ ]:
x.size

5

In [ ]:
type(x)

numpy.ndarray

In [ ]:
x.dtype

dtype('int64')

In [ ]:
x.ndim

1

In [ ]:
y=np.array([
       [1,2,3,4] ,
       [6,7,8,9],
       [10,11,12,13]
            ])
y

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
y.shape


(3, 4)

In [ ]:
y.size

12

In [ ]:
type(y)

numpy.ndarray

In [ ]:
y.dtype

dtype('int64')

In [ ]:
y.ndim

2

In [ ]:
y[0]

array([1, 2, 3, 4])

In [ ]:
y[1][2]          #[row][col]

np.int64(8)

In [ ]:
y[1:,2:]         #row start inx,col start indx

array([[ 8,  9],
       [12, 13]])

In [ ]:
y[1:,1:3]

array([[ 7,  8],
       [11, 12]])

In [ ]:
np.sum(y)   #to find sum of array elements

np.int64(86)

In [ ]:
np.zeros(shape=(3,4))  #creating array filled with zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(shape=(3,3),)  #creating array filled with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:

np.arange(10,20).reshape(5,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

refer and learn

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()  #copying
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))  #joins 2 arrays

print(arr)

[1 2 3 4 5 6]


In [26]:
a=np.array([1,2,3])
for x in a:    #iteration in 1-D array
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:   #iteration in 2-D array
  print(x)

1
2
3
[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)   #spliting the array into 3

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)  #finding the index of element

print(x)

(array([3, 5, 6]),)


In [ ]:
a=np.array([1,2,3,45])
x=a.view()  # creates a new array object that views the same data as the original array.
a[0]=42

print(a)
print(x)

[42  2  3 45]
[42  2  3 45]


In [ ]:
arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

[41 43]


In [ ]:
len(np.arange(10,20).reshape(5,2))  #to finf length

5

In [ ]:
max(a)  #to find max

np.int64(45)

In [ ]:
a=np.array([2,4,6,8,])
range(a)

TypeError: only integer scalar arrays can be converted to a scalar index

In [22]:
import
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

SyntaxError: invalid syntax (ipython-input-22-3818867676.py, line 1)

In [25]:
#statistics
data = np.array([10, 20, 30, 40])
print("Mean:", np.mean(data))
print("Standard Deviation:", np.std(data))
print("Median:", np.median(data))
print("Minimum:", np.min(data))
print("Maximum:", np.max(data))


Mean: 25.0
Standard Deviation: 11.180339887498949
Median: 25.0
Minimum: 10
Maximum: 40


In [24]:
#Linear algebra
matrix = np.array([[1, 2], [3, 4]])
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)


Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
#np.i,np.full,np.insert,np.append,np.delete